print("Første raden:")
første = input()
print("Andre raden:")
andre = input()
print("Tredje raden:")
tredje = input()
len(første)
len(andre)
len(tredje)
ramme = max(len(første), len(andre), len(tredje))

print()
hel_rekke = ((ramme)*"@"+4*"@")
print(hel_rekke)
print("@    " + første + " @")
print("@ " + andre + " @")
print("@        " + tredje + " @")
print(hel_rekke)