print("Hva er ditt navn?")
navn = input()
print("Hva er din adresse?")
adresse = input()
print("Hva er ditt postnummer og poststed?")
post = input()
print(navn + "s adresse er:")
print()
print(navn)
print(adresse)
print(post)
